name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # 只要你打个标签（如 v0.1.0）并推送到 GitHub，就会触发

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install build dependencies
      run: pip install build

    - name: Build binary wheel and source tarball
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
